import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c1c1ff",
        "surface-tint": "#c1c1ff",
        "surface-container-low": "#1b1b1f",
        "on-tertiary-fixed-variant": "#891e00",
        "on-surface": "#e4e1e7",
        "on-tertiary-fixed": "#3c0800",
        outline: "#908fa3",
        tertiary: "#ffb4a1",
        "on-tertiary-container": "#ffc0b0",
        "on-primary-fixed": "#08006c",
        "inverse-primary": "#3f3bfc",
        background: "#131317",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-tertiary": "#611200",
        "on-primary": "#1200a9",
        "tertiary-fixed": "#ffdbd2",
        "on-secondary-fixed": "#09006b",
        "outline-variant": "#454557",
        "surface-container": "#1f1f23",
        "on-secondary-container": "#b1b1ff",
        "tertiary-container": "#a82700",
        "on-secondary": "#1500a8",
        "inverse-on-surface": "#303034",
        "primary-container": "#3832f6",
        error: "#ffb4ab",
        "secondary-container": "#2e26d3",
        "surface-bright": "#39393d",
        "on-background": "#e4e1e7",
        "on-primary-container": "#cbcaff",
        "primary-fixed-dim": "#c1c1ff",
        "on-primary-fixed-variant": "#2008e7",
        "tertiary-fixed-dim": "#ffb4a1",
        "surface-variant": "#353439",
        surface: "#131317",
        secondary: "#c1c1ff",
        "secondary-fixed": "#e1dfff",
        "surface-container-lowest": "#0e0e12",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#2a292e",
        "on-surface-variant": "#c6c4da",
        "on-secondary-fixed-variant": "#2b22d0",
        "primary-fixed": "#e1dfff",
        "surface-container-highest": "#353439",
        primary: "#c1c1ff",
        "surface-dim": "#131317",
        "inverse-surface": "#e4e1e7",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
